Add search functionality
valarao/chocolate-thunder-chess pull request #71
Opened 2021-06-20 05:50 UTC by austincho

**Overview**
-
The changes in this PR connects the backend `/search` endpoint with the redux data store in the front end and allows for the ability to search for positions using the search bar. Resolves #42 and unblocks #43.

We likely want to implement a loading spinner while we wait for the response from the backend. My plan is to work on the loading spinner when I work on the paginations for searches that result in over 9 positions (#43).

2021-06-20 16:41 UTC, valarao requested changes
Great work, Austin - left a few comments.

Also, I noted a potential backend issue: When I try to search "defense", nothing shows up (even though a lot of openings start with defense). In addition to addressing my comments, can you double check the searching algorithm? 

Thanks and let me know if you have any questions!

2021-06-20 16:41 UTC, valarao commented on client/src/redux/reducers/positionReducer.js
> +    case CURRENT_POSITION:
Needs to be named better as an "action" - probably `SET_CURRENT_POSITIONS`

2021-06-20 16:41 UTC, valarao commented on client/src/components/dashboard/SearchBar.js
> +  function onKeyDown(e) {
Convert to arrow function for standardization

2021-06-20 16:41 UTC, valarao commented on client/src/components/dashboard/SearchBar.js
> +  function onClick() {
Convert to arrow function for standardization

2021-06-20 16:41 UTC, valarao commented on client/src/components/dashboard/PositionCard.js
> +        name={nameToUse}
Hmm, I thought what we discussed was to only show the base opening name card. And then when we click on the base opening card, we'll show a dropdown of variations or something.

2021-06-20 16:41 UTC, valarao commented on client/src/redux/reducers/positionReducer.js
> +      case SWITCH_TO_COMMON:
Don't think it makes sense to have this action

2021-06-20 16:41 UTC, valarao commented on client/src/redux/reducers/positionReducer.js
>      case GET_COMMON_POSITIONS:
I wouldn't consolidate setting `currentPositions` in the same reducer. Rather, just make two dispatches.

2021-06-23 23:31 UTC, austincho commented
> Great work, Austin - left a few comments.
> 
> Also, I noted a potential backend issue: When I try to search "defense", nothing shows up (even though a lot of openings start with defense). In addition to addressing my comments, can you double check the searching algorithm?
> 
> Thanks and let me know if you have any questions!

Hey Miguel, currently when the search happens it looks if the baseOpening.name field or the variation field contains what you searched. I believe the issue that you're running into is because of the fact that the our data uses the "Defence" spelling vs "Defense".

2021-06-24 22:07 UTC, valarao approved these changes
LGTM!

2021-06-24 22:09 UTC, joyx9 approved these changes

2021-06-24 22:13 UTC, merged